services:
  # --- Web App Laravel (usa Dockerfile) ---
  - type: web
    name: controle-estoque-app
    env: docker
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader \
      && npm install \
      && npm run build \
      && php artisan storage:link \
      && php artisan migrate --force
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Controle de Estoque"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:iz4lv8GTwGcEEwoTvhJ6q5QSrr/pDa4UjmdZHFnD5jI=
      - key: APP_DEBUG
        value: false
      # >>> Preencha manualmente no painel da Render <<<
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: your-db-host.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password

  # --- Banco de Dados PostgreSQL ---
  - type: pserv
    name: controle-estoque-db
    env: postgres
    plan: free

  # --- Worker para Scheduler ---
  - type: worker
    name: laravel-scheduler
    env: docker
    plan: free
    buildCommand: ""
    startCommand: |
      while true; do
        php artisan schedule:run
        sleep 60
      done
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: your-db-host.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
