services:
  # --- Serviço Web (Laravel usando Dockerfile) ---
  - type: web
    name: controle-estoque-app
    env: docker Dockerfile
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader \
      && npm install \
      && npm run build \
      && php artisan storage:link \
      && php artisan migrate --force
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Controle de Estoque"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:iz4lv8GTwGcEEwoTvhJ6q5QSrr/pDa4UjmdZHFnD5jI=
      - key: APP_DEBUG
        value: false

  # --- Banco de Dados PostgreSQL ---
  - type: pserv
    name: controle-estoque-db
    env: postgres
    plan: free

  # --- Worker para Scheduler ---
  - type: worker
    name: laravel-scheduler
    env: docker
    plan: free
    buildCommand: ""
    startCommand: |
      while true; do
        php artisan schedule:run
        sleep 60
      done
    envVars:
