services:
  # --- Serviço Web Principal (Sua Aplicação Laravel) ---
  - type: web
    name: controle-estoque-app
    env: php
    plan: free
    buildCommand: "composer install && npm install && npm run build && php artisan migrate:fresh --seed && php artisan storage:link"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PHP_VERSION
        value: '8.2'
      - key: APP_NAME
        value: "Controle de Estoque"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:iz4lv8GTwGcEEwoTvhJ6q5QSrr/pDa4UjmdZHFnD5jI=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: controle-estoque-app
          property: url
      - key: LOG_CHANNEL
        value: stderr
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: controle-estoque-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      # --- Variáveis do Mailtrap ---
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_USERNAME
        value: e8afe66f633fdc
      - key: MAIL_PASSWORD
        value: 15da2ec7882cbc
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: "alertas@estoque.com"
      - key: MAIL_FROM_NAME
        value: "Controle de Estoque"

  # --- Banco de Dados PostgreSQL ---
  - type: pserv
    name: controle-estoque-db
    env: postgres
    plan: free

  # --- Cron Job para o Agendador ---
  - type: cron
    name: laravel-scheduler
    plan: free
    env: php
    schedule: "* * * * *"
    command: "php artisan schedule:run"
