services:
  # --- Aplicação Laravel (Docker) ---
  - type: web
    name: controle-estoque-app
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: controle-estoque-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: controle-estoque-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: controle-estoque-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: controle-estoque-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: controle-estoque-db
          property: password

databases:
  - name: controle-estoque-db
    plan: free
